from typing import Optional
from app.services.llm.factory import get_llm_provider

async def generate_response(prompt: str, system_instruction: Optional[str] = None) -> str:
    """
    Convenience function to generate a response from the configured LLM provider asynchronously.
    
    Args:
        prompt (str): The input text for the LLM.
        system_instruction (Optional[str]): Behavior or persona instructions.
        
    Returns:
        str: The response generated by the active LLM.
    """
    provider = get_llm_provider()
    return await provider.generate(prompt, system_instruction=system_instruction)
